In [4]:
import pandas as pd
import os

In [23]:
train_data = pd.read_csv(os.path.join(os.path.split(os.getcwd())[0], "SYD_DAT_5/data/sydtrains.csv"))

In [29]:
train_data.describe()

,YEAR,IN_0200_0600,OUT_0200_0600,IN_0600_0930,OUT_0600_0930,IN_0930_1500,OUT_0930_1500,IN_1500_1830,OUT_1500_1830,IN_1830_0200,OUT_1830_0200,RANK,STATION_SORT_ID
count,3367.000000,3367.000000,3367.000000,3367.000000,3367.000000,3367.000000,3367.000000,3367.000000,3367.000000,3367.000000,3367.000000,3367.000000,3367.000000
mean,2009.013959,47.528958,29.364419,1061.749332,1010.986041,712.803683,727.635878,1093.415503,1036.587467,324.359964,435.533116,152.623701,1190.570241
std,3.164360,96.815978,78.484683,1480.814320,4061.525304,1710.546289,2208.697265,4081.289303,1667.241032,1524.362855,789.198548,87.295273,577.821823
min,2004.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,101.000000
25%,2006.000000,10.000000,0.000000,90.000000,20.000000,40.000000,30.000000,30.000000,90.000000,10.000000,30.000000,77.000000,617.000000
50%,2009.000000,20.000000,10.000000,460.000000,140.000000,220.000000,190.000000,180.000000,410.000000,40.000000,150.000000,153.000000,1308.000000
75%,2012.000000,50.000000,20.000000,1430.000000,530.000000,620.000000,570.000000,590.000000,1300.000000,120.000000,480.000000,230.000000,1703.000000
max,2014.000000,940.000000,920.000000,10630.000000,43210.000000,21400.000000,30940.000000,45370.000000,16270.000000,24200.000000,7700.000000,299.000000,2029.000000

In [26]:
train_data2014 = train_data[train_data.YEAR==2014]

In [27]:
train_data2014

,LINE,STATION,YEAR,SURVEY_DATE_USED,WHETHER_SURVEYED,IN_0200_0600,OUT_0200_0600,IN_0600_0930,OUT_0600_0930,IN_0930_1500,OUT_0930_1500,IN_1500_1830,OUT_1500_1830,IN_1830_0200,OUT_1830_0200,IN_24_HOURS,OUT_24_HOURS,RANK,STATION_SORT_ID
0,CBD,Central,2014,6/05/2014,Yes,940,920,10390,42070,21400,30150,45370,16270,19010,7700,"97,110","97,110",1,101
1,CBD,Town Hall,2014,7/05/2014,Yes,880,880,6380,43210,16930,23550,43670,15270,21760,6720,"89,620","89,620",2,102
2,CBD,Wynyard,2014,20/05/2014,Yes,590,570,4710,39620,9200,11180,35010,6510,10690,2330,"60,200","60,200",3,103
3,Western,Parramatta,2014,19/11/2014,Yes,660,330,7790,13700,7400,7020,14960,8660,4150,5260,"34,960","34,960",4,905
4,North Shore,North Sydney,2014,19/08/2014,Yes,270,270,2340,18340,4450,5590,17760,3050,3790,1360,"28,610","28,610",5,1402
5,CBD,Redfern,2014,1/05/2014,Yes,250,250,3910,10690,5350,8170,12510,4250,3660,2320,"25,680","25,680",6,108
6,North Shore,Chatswood,2014,19/08/2014,Yes,210,200,5030,8200,4710,4930,9430,6000,2820,2860,"22,200","22,200",7,1407
7,Eastern Suburbs,Bondi Junction,2014,2/09/2014,Yes,210,210,10150,4350,4370,4600,5240,8330,1910,4380,"21,880","21,880",8,203
8,Inner West,Strathfield,2014,9/09/2014,Yes,190,190,7900,4050,4980,3950,5540,7230,2100,5280,"20,710","20,710",9,1110
9,CBD,Circular Quay,2014,22/05/2014,Yes,200,200,2110,8750,4340,6710,9910,3380,4070,1600,"20,630","20,630",10,104
10,CBD,Martin Place,2014,27/05/2014,Yes,200,190,590,14250,2900,3420,12340,1790,4600,970,"20,630","20,630",10,107
11,Illawarra,Hurstville,2014,28/05/2014,Yes,160,160,7790,2200,5230,4180,3840,7450,1270,4290,"18,290","18,290",12,310
12,North Shore,St Leonards,2014,27/05/2014,Yes,170,170,3420,8900,3090,3310,8780,3230,2130,1990,"17,590","17,590",13,1405
13,Western,Blacktown,2014,14/10/2014,Yes,190,210,6460,3370,4270,3450,4600,7090,1040,2450,"16,560","16,560",14,911
14,Inner West,Burwood,2014,9/09/2014,Yes,140,140,4850,2930,4470,3670,4020,5060,1510,3190,"14,990","14,990",15,1109
15,Eastern Suburbs,Kings Cross,2014,3/09/2013,No,120,120,3690,3820,3110,2670,4400,3640,1550,2620,"12,870","12,870",16,201
16,North Shore,Hornsby,2014,14/05/2014,Yes,210,100,5550,2260,3060,2390,2750,5200,680,2290,"12,250","12,250",17,1417
17,Inner West,Ashfield,2014,4/09/2013,No,100,100,5090,2010,2690,2220,2500,4500,820,2370,"11,200","11,200",18,1107
18,Illawarra,Kogarah,2014,19/06/2014,Yes,90,100,4000,2970,3150,2320,3210,3450,650,2260,"11,100","11,100",19,307
19,South,Lidcombe,2014,5/06/2014,Yes,100,100,4570,1620,2870,2210,2550,3900,820,3080,"10,910","10,910",20,702
20,Western,Auburn,2014,19/11/2014,Yes,130,60,3880,1790,3220,2900,2700,3890,960,2260,"10,890","10,890",21,901
21,CBD,Museum,2014,22/05/2014,Yes,100,100,800,6290,2220,2340,5980,1230,1760,910,"10,860","10,860",22,106
22,Northern via Strathfield,Epping,2014,21/05/2014,Yes,170,90,5700,1580,2130,1600,1970,4920,600,2380,"10,570","10,570",23,1208
23,Northern via Macquarie Park,Macquarie University,2014,21/05/2014,Yes,100,100,1310,3220,2570,3940,4530,1970,1580,860,"10,090","10,090",24,1303
24,CBD,St James,2014,27/05/2014,Yes,100,90,780,5880,1900,2160,5630,1120,1440,580,"9,850","9,850",25,105
25,Illawarra,Rockdale,2014,28/05/2014,Yes,90,90,4660,780,2610,2170,1670,3770,610,2820,"9,640","9,640",26,306
26,South,Cabramatta,2014,11/06/2014,Yes,150,80,3780,1070,2760,2820,1750,3760,290,1000,"8,730","8,730",27,708
27,Bankstown,Bankstown,2014,13/05/2014,Yes,80,60,3010,1810,2400,2570,2840,3130,300,1050,"8,630","8,630",28,612
28,South,Liverpool,2014,4/06/2014,Yes,150,80,2510,2270,2510,2260,2610,2650,570,1100,"8,350","8,350",29,710
29,Illawarra,Sutherland,2014,12/06/2014,Yes,140,70,4260,1460,1920,1650,1750,3900,250,1240,"8,320","8,320",30,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278,Southern Highlands,Menangle Park,2014,19/06/2014,Yes,0,0,10,0,10,10,0,10,0,0,20,20,277,1601
279,South Coast,Port Kembla North,2014,18/09/2014,Yes,0,0,0,10,10,0,10,10,0,0,20,20,277,1521
280,Hunter,Scone,2014,3/06/2009,No,10,0,0,0,0,0,0,10,10,10,20,20,277,2029
281,Hunter,Tarro,2014,3/06/2009,No,0,0,10,0,10,0,0,10,0,0,20,20,277,2005
282,Hunter,Aberdeen,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,10,10,283,2028
283,South Coast,Bombo,2014,18/09/2014,Yes,0,0,10,0,0,0,0,10,0,0,10,10,283,1530
284,Hunter,Branxton,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,10,10,283,2024
285,Southern Highlands,Burradoo,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,10,10,283,1610
286,South Coast,Coalcliff,2014,9/08/2012,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1504
287,South Coast,Dunmore (Shellharbour),2014,18/06/2014,Yes,0,0,10,0,0,10,0,10,0,0,10,10,283,1528
288,Southern Highlands,Exeter,2014,25/05/2010,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1612
289,Hunter,Greta,2014,3/06/2009,No,0,0,0,0,0,0,0,10,0,0,10,10,283,2023
290,Blue Mountains,Linden,2014,19/08/2014,Yes,0,0,10,0,0,10,0,10,0,0,10,10,283,1708
291,Southern Highlands,Marulan,2014,17/06/2014,Yes,0,0,0,0,0,0,0,0,10,10,10,10,283,1617
292,Southern Highlands,Menangle,2014,17/06/2014,Yes,0,0,10,0,0,0,0,10,0,0,10,10,283,1602
293,Hunter,Paterson,2014,3/06/2009,No,0,0,10,0,0,0,0,10,0,0,10,10,283,2015
294,South Coast,Scarborough,2014,22/08/2013,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1505
295,Southern Highlands,Tallong,2014,25/05/2010,No,0,0,10,0,0,0,0,0,0,10,10,10,283,1616
296,Central Coast,Wondabyne,2014,21/11/2012,No,0,0,0,0,0,0,0,0,0,0,10,10,283,1803
297,Blue Mountains,Bell,2014,0,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1719
298,Hunter,Hilldale,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2017
299,South Coast,Kembla Grange Racecourse,2014,15/02/1996,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1524
300,Hunter,Lochinvar,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2021
301,South Coast,Lysaghts,2014,12/11/2013,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1519
302,Hunter,Mindaribba,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2014
303,Southern Highlands,Penrose,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1614
304,Hunter,Wallarobba,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2018
305,Southern Highlands,Wingello,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1615
306,Hunter,Wirragulla,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2019
307,Blue Mountains,Zig Zag,2014,9/10/2014,Yes,0,0,0,0,0,0,0,0,0,0,0,0,298,1720

In [31]:
train_data2014.IN_0200_0600.idxmin()

46

In [32]:
train_data2014.columns

Index([u'LINE', u'STATION', u'YEAR', u'SURVEY_DATE_USED', u'WHETHER_SURVEYED',
       u'IN_0200_0600', u'OUT_0200_0600', u'IN_0600_0930', u'OUT_0600_0930',
       u'IN_0930_1500', u'OUT_0930_1500', u'IN_1500_1830', u'OUT_1500_1830',
       u'IN_1830_0200', u'OUT_1830_0200', u'IN_24_HOURS', u'OUT_24_HOURS',
       u'RANK', u'STATION_SORT_ID'],
      dtype='object')

In [54]:
train_data = pd.read_csv(os.path.join(os.path.split(os.getcwd())[0], "SYD_DAT_5/data/sydtrains.csv"), index_col=1)

In [55]:
train_data2014 = train_data[train_data.YEAR == 2014]

In [56]:
train_data2014.IN_0200_0600.idxmin()

'Green Square'

In [57]:
train_data2014.IN_0200_0600.sum()

16060

In [52]:
train_data2014

,LINE,YEAR,SURVEY_DATE_USED,WHETHER_SURVEYED,IN_0200_0600,OUT_0200_0600,IN_0600_0930,OUT_0600_0930,IN_0930_1500,OUT_0930_1500,IN_1500_1830,OUT_1500_1830,IN_1830_0200,OUT_1830_0200,IN_24_HOURS,OUT_24_HOURS,RANK,STATION_SORT_ID
STATION,,,,,,,,,,,,,,,,,,
Central,CBD,2014,6/05/2014,Yes,940,920,10390,42070,21400,30150,45370,16270,19010,7700,"97,110","97,110",1,101
Town Hall,CBD,2014,7/05/2014,Yes,880,880,6380,43210,16930,23550,43670,15270,21760,6720,"89,620","89,620",2,102
Wynyard,CBD,2014,20/05/2014,Yes,590,570,4710,39620,9200,11180,35010,6510,10690,2330,"60,200","60,200",3,103
Parramatta,Western,2014,19/11/2014,Yes,660,330,7790,13700,7400,7020,14960,8660,4150,5260,"34,960","34,960",4,905
North Sydney,North Shore,2014,19/08/2014,Yes,270,270,2340,18340,4450,5590,17760,3050,3790,1360,"28,610","28,610",5,1402
Redfern,CBD,2014,1/05/2014,Yes,250,250,3910,10690,5350,8170,12510,4250,3660,2320,"25,680","25,680",6,108
Chatswood,North Shore,2014,19/08/2014,Yes,210,200,5030,8200,4710,4930,9430,6000,2820,2860,"22,200","22,200",7,1407
Bondi Junction,Eastern Suburbs,2014,2/09/2014,Yes,210,210,10150,4350,4370,4600,5240,8330,1910,4380,"21,880","21,880",8,203
Strathfield,Inner West,2014,9/09/2014,Yes,190,190,7900,4050,4980,3950,5540,7230,2100,5280,"20,710","20,710",9,1110
Circular Quay,CBD,2014,22/05/2014,Yes,200,200,2110,8750,4340,6710,9910,3380,4070,1600,"20,630","20,630",10,104
Martin Place,CBD,2014,27/05/2014,Yes,200,190,590,14250,2900,3420,12340,1790,4600,970,"20,630","20,630",10,107
Hurstville,Illawarra,2014,28/05/2014,Yes,160,160,7790,2200,5230,4180,3840,7450,1270,4290,"18,290","18,290",12,310
St Leonards,North Shore,2014,27/05/2014,Yes,170,170,3420,8900,3090,3310,8780,3230,2130,1990,"17,590","17,590",13,1405
Blacktown,Western,2014,14/10/2014,Yes,190,210,6460,3370,4270,3450,4600,7090,1040,2450,"16,560","16,560",14,911
Burwood,Inner West,2014,9/09/2014,Yes,140,140,4850,2930,4470,3670,4020,5060,1510,3190,"14,990","14,990",15,1109
Kings Cross,Eastern Suburbs,2014,3/09/2013,No,120,120,3690,3820,3110,2670,4400,3640,1550,2620,"12,870","12,870",16,201
Hornsby,North Shore,2014,14/05/2014,Yes,210,100,5550,2260,3060,2390,2750,5200,680,2290,"12,250","12,250",17,1417
Ashfield,Inner West,2014,4/09/2013,No,100,100,5090,2010,2690,2220,2500,4500,820,2370,"11,200","11,200",18,1107
Kogarah,Illawarra,2014,19/06/2014,Yes,90,100,4000,2970,3150,2320,3210,3450,650,2260,"11,100","11,100",19,307
Lidcombe,South,2014,5/06/2014,Yes,100,100,4570,1620,2870,2210,2550,3900,820,3080,"10,910","10,910",20,702
Auburn,Western,2014,19/11/2014,Yes,130,60,3880,1790,3220,2900,2700,3890,960,2260,"10,890","10,890",21,901
Museum,CBD,2014,22/05/2014,Yes,100,100,800,6290,2220,2340,5980,1230,1760,910,"10,860","10,860",22,106
Epping,Northern via Strathfield,2014,21/05/2014,Yes,170,90,5700,1580,2130,1600,1970,4920,600,2380,"10,570","10,570",23,1208
Macquarie University,Northern via Macquarie Park,2014,21/05/2014,Yes,100,100,1310,3220,2570,3940,4530,1970,1580,860,"10,090","10,090",24,1303
St James,CBD,2014,27/05/2014,Yes,100,90,780,5880,1900,2160,5630,1120,1440,580,"9,850","9,850",25,105
Rockdale,Illawarra,2014,28/05/2014,Yes,90,90,4660,780,2610,2170,1670,3770,610,2820,"9,640","9,640",26,306
Cabramatta,South,2014,11/06/2014,Yes,150,80,3780,1070,2760,2820,1750,3760,290,1000,"8,730","8,730",27,708
Bankstown,Bankstown,2014,13/05/2014,Yes,80,60,3010,1810,2400,2570,2840,3130,300,1050,"8,630","8,630",28,612
Liverpool,South,2014,4/06/2014,Yes,150,80,2510,2270,2510,2260,2610,2650,570,1100,"8,350","8,350",29,710
Sutherland,Illawarra,2014,12/06/2014,Yes,140,70,4260,1460,1920,1650,1750,3900,250,1240,"8,320","8,320",30,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Menangle Park,Southern Highlands,2014,19/06/2014,Yes,0,0,10,0,10,10,0,10,0,0,20,20,277,1601
Port Kembla North,South Coast,2014,18/09/2014,Yes,0,0,0,10,10,0,10,10,0,0,20,20,277,1521
Scone,Hunter,2014,3/06/2009,No,10,0,0,0,0,0,0,10,10,10,20,20,277,2029
Tarro,Hunter,2014,3/06/2009,No,0,0,10,0,10,0,0,10,0,0,20,20,277,2005
Aberdeen,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,10,10,283,2028
Bombo,South Coast,2014,18/09/2014,Yes,0,0,10,0,0,0,0,10,0,0,10,10,283,1530
Branxton,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,10,10,283,2024
Burradoo,Southern Highlands,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,10,10,283,1610
Coalcliff,South Coast,2014,9/08/2012,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1504
Dunmore (Shellharbour),South Coast,2014,18/06/2014,Yes,0,0,10,0,0,10,0,10,0,0,10,10,283,1528
Exeter,Southern Highlands,2014,25/05/2010,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1612
Greta,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,10,0,0,10,10,283,2023
Linden,Blue Mountains,2014,19/08/2014,Yes,0,0,10,0,0,10,0,10,0,0,10,10,283,1708
Marulan,Southern Highlands,2014,17/06/2014,Yes,0,0,0,0,0,0,0,0,10,10,10,10,283,1617
Menangle,Southern Highlands,2014,17/06/2014,Yes,0,0,10,0,0,0,0,10,0,0,10,10,283,1602
Paterson,Hunter,2014,3/06/2009,No,0,0,10,0,0,0,0,10,0,0,10,10,283,2015
Scarborough,South Coast,2014,22/08/2013,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1505
Tallong,Southern Highlands,2014,25/05/2010,No,0,0,10,0,0,0,0,0,0,10,10,10,283,1616
Wondabyne,Central Coast,2014,21/11/2012,No,0,0,0,0,0,0,0,0,0,0,10,10,283,1803
Bell,Blue Mountains,2014,0,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1719
Hilldale,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2017
Kembla Grange Racecourse,South Coast,2014,15/02/1996,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1524
Lochinvar,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2021
Lysaghts,South Coast,2014,12/11/2013,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1519
Mindaribba,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2014
Penrose,Southern Highlands,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1614
Wallarobba,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2018
Wingello,Southern Highlands,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1615
Wirragulla,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2019
Zig Zag,Blue Mountains,2014,9/10/2014,Yes,0,0,0,0,0,0,0,0,0,0,0,0,298,1720

In [53]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, skipfooter=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal='.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=False, error_bad_lines=True, warn_bad_lines=True, skip_footer=0, doublequote=True, delim_whitespace=False, as_recarray=False, compact_ints=False, use_unsigned=False, low_memory=True, buffer_lines=None, memory_map=False, float_precision=None)
    Read CSV (comma-separated) file into DataFrame

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the `online docs for IO Tools
    <http://pandas.pydata.org/pandas-docs/stable/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, pathlib.Path, py._path.local.LocalPath or any object with a read() method (such as a file handle or StringIO)
        The string could be a URL. Valid URL schemes include http, ftp, s3, and
        file. For file URLs, a host is expected. For instance, a local file could
        be file ://localhost/path/to/table.csv
    sep : str, default ','
        Delimiter to use. If sep is None, will try to automatically determine
        this. Separators longer than 1 character and different from '\s+' will be
        interpreted as regular expressions, will force use of the python parsing
        engine and will ignore quotes in the data. Regex example: '\r\t'
    delimiter : str, default ``None``
        Alternative argument name for sep.
    delim_whitespace : boolean, default False
        Specifies whether or not whitespace (e.g. ``' '`` or ``'    '``) will be
        used as the sep. Equivalent to setting ``sep='\+s'``. If this option
        is set to True, nothing should be passed in for the ``delimiter``
        parameter.

        .. versionadded:: 0.18.1 support for the Python parser.

    header : int or list of ints, default 'infer'
        Row number(s) to use as the column names, and the start of the data.
        Default behavior is as if set to 0 if no ``names`` passed, otherwise
        ``None``. Explicitly pass ``header=0`` to be able to replace existing
        names. The header can be a list of integers that specify row locations for
        a multi-index on the columns e.g. [0,1,3]. Intervening rows that are not
        specified will be skipped (e.g. 2 in this example is skipped). Note that
        this parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so header=0 denotes the first line of data
        rather than the first line of the file.
    names : array-like, default None
        List of column names to use. If file contains no header row, then you
        should explicitly pass header=None
    index_col : int or sequence or False, default None
        Column to use as the row labels of the DataFrame. If a sequence is given, a
        MultiIndex is used. If you have a malformed file with delimiters at the end
        of each line, you might consider index_col=False to force pandas to _not_
        use the first column as the index (row names)
    usecols : array-like, default None
        Return a subset of the columns. All elements in this array must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in `names` or
        inferred from the document header row(s). For example, a valid `usecols`
        parameter would be [0, 1, 2] or ['foo', 'bar', 'baz']. Using this parameter
        results in much faster parsing time and lower memory usage.
    squeeze : boolean, default False
        If the parsed data only contains one column then return a Series
    prefix : str, default None
        Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...
    mangle_dupe_cols : boolean, default True
        Duplicate columns will be specified as 'X.0'...'X.N', rather than 'X'...'X'
    dtype : Type name or dict of column -> type, default None
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
        (Unsupported with engine='python'). Use `str` or `object` to preserve and
        not interpret dtype.
    engine : {'c', 'python'}, optional
        Parser engine to use. The C engine is faster while the python engine is
        currently more feature-complete.
    converters : dict, default None
        Dict of functions for converting values in certain columns. Keys can either
        be integers or column labels
    true_values : list, default None
        Values to consider as True
    false_values : list, default None
        Values to consider as False
    skipinitialspace : boolean, default False
        Skip spaces after delimiter.
    skiprows : list-like or integer, default None
        Line numbers to skip (0-indexed) or number of lines to skip (int)
        at the start of the file
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with engine='c')
    nrows : int, default None
        Number of rows of file to read. Useful for reading pieces of large files
    na_values : str or list-like or dict, default None
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values.  By default the following values are interpreted as
        NaN: `''`, `'#N/A'`, `'#N/A N/A'`, `'#NA'`, `'-1.#IND'`, `'-1.#QNAN'`, `'-NaN'`, `'-nan'`, `'1.#IND'`, `'1.#QNAN'`, `'N/A'`, `'NA'`, `'NULL'`, `'NaN'`, `'nan'`.
    keep_default_na : bool, default True
        If na_values are specified and keep_default_na is False the default NaN
        values are overridden, otherwise they're appended to.
    na_filter : boolean, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing na_filter=False can improve the performance
        of reading a large file
    verbose : boolean, default False
        Indicate number of NA values placed in non-numeric columns
    skip_blank_lines : boolean, default True
        If True, skip over blank lines rather than interpreting as NaN values
    parse_dates : boolean or list of ints or names or list of lists or dict, default False

        * boolean. If True -> try parsing the index.
        * list of ints or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
            a single date column.
        * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call result
          'foo'

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : boolean, default False
        If True and parse_dates is enabled, pandas will attempt to infer the format
        of the datetime strings in the columns, and if it can be inferred, switch
        to a faster method of parsing them. In some cases this can increase the
        parsing speed by ~5-10x.
    keep_date_col : boolean, default False
        If True and parse_dates specifies combining multiple columns then
        keep the original columns.
    date_parser : function, default None
        Function to use for converting a sequence of string columns to an array of
        datetime instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. Pandas will try to call date_parser in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by parse_dates) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by parse_dates into a single array
        and pass that; and 3) call date_parser once for each row using one or more
        strings (corresponding to the columns defined by parse_dates) as arguments.
    dayfirst : boolean, default False
        DD/MM format dates, international and European format
    iterator : boolean, default False
        Return TextFileReader object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, default None
        Return TextFileReader object for iteration. `See IO Tools docs for more
        information
        <http://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_ on
        ``iterator`` and ``chunksize``.
    compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer', then use gzip,
        bz2, zip or xz if filepath_or_buffer is a string ending in '.gz', '.bz2',
        '.zip', or 'xz', respectively, and no decompression otherwise. If using
        'zip', the ZIP file must contain only one data file to be read in.
        Set to None for no decompression.

        .. versionadded:: 0.18.1 support for 'zip' and 'xz' compression.

    thousands : str, default None
        Thousands separator
    decimal : str, default '.'
        Character to recognize as decimal point (e.g. use ',' for European data).
    lineterminator : str (length 1), default None
        Character to break file into lines. Only valid with C parser.
    quotechar : str (length 1), optional
        The character used to denote the start and end of a quoted item. Quoted
        items can include the delimiter and it will be ignored.
    quoting : int or csv.QUOTE_* instance, default None
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
        QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
        Default (None) results in QUOTE_MINIMAL behavior.
    escapechar : str (length 1), default None
        One-character string used to escape delimiter when quoting is QUOTE_NONE.
    comment : str, default None
        Indicates remainder of line should not be parsed. If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter `header` but not by
        `skiprows`. For example, if comment='#', parsing '#empty\na,b,c\n1,2,3'
        with `header=0` will result in 'a,b,c' being
        treated as the header.
    encoding : str, default None
        Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_
    dialect : str or csv.Dialect instance, default None
        If None defaults to Excel dialect. Ignored if sep longer than 1 char
        See csv.Dialect documentation for more details
    tupleize_cols : boolean, default False
        Leave a list of tuples on columns as is (default is to convert to
        a Multi Index on the columns)
    error_bad_lines : boolean, default True
        Lines with too many fields (e.g. a csv line with too many commas) will by
        default cause an exception to be raised, and no DataFrame will be returned.
        If False, then these "bad lines" will dropped from the DataFrame that is
        returned. (Only valid with C parser)
    warn_bad_lines : boolean, default True
        If error_bad_lines is False, and warn_bad_lines is True, a warning for each
        "bad line" will be output. (Only valid with C parser).

    Returns
    -------
    result : DataFrame or TextParser

In [58]:
train_data = pd.read_csv(os.path.join(os.path.split(os.getcwd())[0], "SYD_DAT_5/data/sydtrains.csv"), index_col=1, thousands=',')

In [60]:
train_data2014 = train_data[train_data.YEAR == 2014]

In [65]:
train_data2014.IN_24_HOURS

STATION
Central                     97110
Town Hall                   89620
Wynyard                     60200
Parramatta                  34960
North Sydney                28610
Redfern                     25680
Chatswood                   22200
Bondi Junction              21880
Strathfield                 20710
Circular Quay               20630
Martin Place                20630
Hurstville                  18290
St Leonards                 17590
Blacktown                   16560
Burwood                     14990
Kings Cross                 12870
Hornsby                     12250
Ashfield                    11200
Kogarah                     11100
Lidcombe                    10910
Auburn                      10890
Museum                      10860
Epping                      10570
Macquarie University        10090
St James                     9850
Rockdale                     9640
Cabramatta                   8730
Bankstown                    8630
Liverpool                    8350
Sutherland                   8320
                            ...
Menangle Park                  20
Port Kembla North              20
Scone                          20
Tarro                          20
Aberdeen                       10
Bombo                          10
Branxton                       10
Burradoo                       10
Coalcliff                      10
Dunmore (Shellharbour)         10
Exeter                         10
Greta                          10
Linden                         10
Marulan                        10
Menangle                       10
Paterson                       10
Scarborough                    10
Tallong                        10
Wondabyne                      10
Bell                            0
Hilldale                        0
Kembla Grange Racecourse        0
Lochinvar                       0
Lysaghts                        0
Mindaribba                      0
Penrose                         0
Wallarobba                      0
Wingello                        0
Wirragulla                      0
Zig Zag                         0
Name: IN_24_HOURS, dtype: int64

In [72]:
train_data2014

,LINE,YEAR,SURVEY_DATE_USED,WHETHER_SURVEYED,IN_0200_0600,OUT_0200_0600,IN_0600_0930,OUT_0600_0930,IN_0930_1500,OUT_0930_1500,IN_1500_1830,OUT_1500_1830,IN_1830_0200,OUT_1830_0200,IN_24_HOURS,OUT_24_HOURS,RANK,STATION_SORT_ID
STATION,,,,,,,,,,,,,,,,,,
Central,CBD,2014,6/05/2014,Yes,940,920,10390,42070,21400,30150,45370,16270,19010,7700,97110,97110,1,101
Town Hall,CBD,2014,7/05/2014,Yes,880,880,6380,43210,16930,23550,43670,15270,21760,6720,89620,89620,2,102
Wynyard,CBD,2014,20/05/2014,Yes,590,570,4710,39620,9200,11180,35010,6510,10690,2330,60200,60200,3,103
Parramatta,Western,2014,19/11/2014,Yes,660,330,7790,13700,7400,7020,14960,8660,4150,5260,34960,34960,4,905
North Sydney,North Shore,2014,19/08/2014,Yes,270,270,2340,18340,4450,5590,17760,3050,3790,1360,28610,28610,5,1402
Redfern,CBD,2014,1/05/2014,Yes,250,250,3910,10690,5350,8170,12510,4250,3660,2320,25680,25680,6,108
Chatswood,North Shore,2014,19/08/2014,Yes,210,200,5030,8200,4710,4930,9430,6000,2820,2860,22200,22200,7,1407
Bondi Junction,Eastern Suburbs,2014,2/09/2014,Yes,210,210,10150,4350,4370,4600,5240,8330,1910,4380,21880,21880,8,203
Strathfield,Inner West,2014,9/09/2014,Yes,190,190,7900,4050,4980,3950,5540,7230,2100,5280,20710,20710,9,1110
Circular Quay,CBD,2014,22/05/2014,Yes,200,200,2110,8750,4340,6710,9910,3380,4070,1600,20630,20630,10,104
Martin Place,CBD,2014,27/05/2014,Yes,200,190,590,14250,2900,3420,12340,1790,4600,970,20630,20630,10,107
Hurstville,Illawarra,2014,28/05/2014,Yes,160,160,7790,2200,5230,4180,3840,7450,1270,4290,18290,18290,12,310
St Leonards,North Shore,2014,27/05/2014,Yes,170,170,3420,8900,3090,3310,8780,3230,2130,1990,17590,17590,13,1405
Blacktown,Western,2014,14/10/2014,Yes,190,210,6460,3370,4270,3450,4600,7090,1040,2450,16560,16560,14,911
Burwood,Inner West,2014,9/09/2014,Yes,140,140,4850,2930,4470,3670,4020,5060,1510,3190,14990,14990,15,1109
Kings Cross,Eastern Suburbs,2014,3/09/2013,No,120,120,3690,3820,3110,2670,4400,3640,1550,2620,12870,12870,16,201
Hornsby,North Shore,2014,14/05/2014,Yes,210,100,5550,2260,3060,2390,2750,5200,680,2290,12250,12250,17,1417
Ashfield,Inner West,2014,4/09/2013,No,100,100,5090,2010,2690,2220,2500,4500,820,2370,11200,11200,18,1107
Kogarah,Illawarra,2014,19/06/2014,Yes,90,100,4000,2970,3150,2320,3210,3450,650,2260,11100,11100,19,307
Lidcombe,South,2014,5/06/2014,Yes,100,100,4570,1620,2870,2210,2550,3900,820,3080,10910,10910,20,702
Auburn,Western,2014,19/11/2014,Yes,130,60,3880,1790,3220,2900,2700,3890,960,2260,10890,10890,21,901
Museum,CBD,2014,22/05/2014,Yes,100,100,800,6290,2220,2340,5980,1230,1760,910,10860,10860,22,106
Epping,Northern via Strathfield,2014,21/05/2014,Yes,170,90,5700,1580,2130,1600,1970,4920,600,2380,10570,10570,23,1208
Macquarie University,Northern via Macquarie Park,2014,21/05/2014,Yes,100,100,1310,3220,2570,3940,4530,1970,1580,860,10090,10090,24,1303
St James,CBD,2014,27/05/2014,Yes,100,90,780,5880,1900,2160,5630,1120,1440,580,9850,9850,25,105
Rockdale,Illawarra,2014,28/05/2014,Yes,90,90,4660,780,2610,2170,1670,3770,610,2820,9640,9640,26,306
Cabramatta,South,2014,11/06/2014,Yes,150,80,3780,1070,2760,2820,1750,3760,290,1000,8730,8730,27,708
Bankstown,Bankstown,2014,13/05/2014,Yes,80,60,3010,1810,2400,2570,2840,3130,300,1050,8630,8630,28,612
Liverpool,South,2014,4/06/2014,Yes,150,80,2510,2270,2510,2260,2610,2650,570,1100,8350,8350,29,710
Sutherland,Illawarra,2014,12/06/2014,Yes,140,70,4260,1460,1920,1650,1750,3900,250,1240,8320,8320,30,316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Menangle Park,Southern Highlands,2014,19/06/2014,Yes,0,0,10,0,10,10,0,10,0,0,20,20,277,1601
Port Kembla North,South Coast,2014,18/09/2014,Yes,0,0,0,10,10,0,10,10,0,0,20,20,277,1521
Scone,Hunter,2014,3/06/2009,No,10,0,0,0,0,0,0,10,10,10,20,20,277,2029
Tarro,Hunter,2014,3/06/2009,No,0,0,10,0,10,0,0,10,0,0,20,20,277,2005
Aberdeen,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,10,10,283,2028
Bombo,South Coast,2014,18/09/2014,Yes,0,0,10,0,0,0,0,10,0,0,10,10,283,1530
Branxton,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,10,10,283,2024
Burradoo,Southern Highlands,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,10,10,283,1610
Coalcliff,South Coast,2014,9/08/2012,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1504
Dunmore (Shellharbour),South Coast,2014,18/06/2014,Yes,0,0,10,0,0,10,0,10,0,0,10,10,283,1528
Exeter,Southern Highlands,2014,25/05/2010,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1612
Greta,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,10,0,0,10,10,283,2023
Linden,Blue Mountains,2014,19/08/2014,Yes,0,0,10,0,0,10,0,10,0,0,10,10,283,1708
Marulan,Southern Highlands,2014,17/06/2014,Yes,0,0,0,0,0,0,0,0,10,10,10,10,283,1617
Menangle,Southern Highlands,2014,17/06/2014,Yes,0,0,10,0,0,0,0,10,0,0,10,10,283,1602
Paterson,Hunter,2014,3/06/2009,No,0,0,10,0,0,0,0,10,0,0,10,10,283,2015
Scarborough,South Coast,2014,22/08/2013,No,0,0,10,0,0,0,0,10,0,0,10,10,283,1505
Tallong,Southern Highlands,2014,25/05/2010,No,0,0,10,0,0,0,0,0,0,10,10,10,283,1616
Wondabyne,Central Coast,2014,21/11/2012,No,0,0,0,0,0,0,0,0,0,0,10,10,283,1803
Bell,Blue Mountains,2014,0,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1719
Hilldale,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2017
Kembla Grange Racecourse,South Coast,2014,15/02/1996,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1524
Lochinvar,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2021
Lysaghts,South Coast,2014,12/11/2013,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1519
Mindaribba,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2014
Penrose,Southern Highlands,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1614
Wallarobba,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2018
Wingello,Southern Highlands,2014,25/05/2010,No,0,0,0,0,0,0,0,0,0,0,0,0,298,1615
Wirragulla,Hunter,2014,3/06/2009,No,0,0,0,0,0,0,0,0,0,0,0,0,298,2019
Zig Zag,Blue Mountains,2014,9/10/2014,Yes,0,0,0,0,0,0,0,0,0,0,0,0,298,1720